// Entry of the webview bundle (dist/preflight-core.js, built by scripts/build.mjs) for the
// hosts without a Node runtime (JetBrains plugin): exposes globalThis.PreflightCore, with
// the AWS icon index computed at build time.

const { buildViewModel } = require('./viewModel');
// @ts-ignore: virtual module generated by scripts/build.mjs from media/aws-icons.
const index = require('preflight:icons');

const icons = new Map(Object.entries(index.services));
const categoryIcons = new Map(Object.entries(index.categories));

globalThis.PreflightCore = {
	/**
	 * @param {string} text JSON plan or state
	 * @param {{ iconUri: (rel: string) => string, modulesJson?: string | null }} opts
	 */
	buildViewModel: (text, opts) => buildViewModel(text, Object.assign({ icons, categoryIcons }, opts))
};
